export const goals = {
  1: {
    // TK A
    energi_kkal: 1350,
    protein_g: 20,
    lemak_g: 45,
    karbohidrat_g: 215,
    serat_g: 19,
    // abu_g: 5, // optional, tidak tercantum di AKG resmi
    // kalsium_mg: 1000,
    // fosfor_mg: 500,
    // besi_mg: 10,
    // natrium_mg: 1000,
    // kalium_mg: 3200,
    // tembaga_mg: 570,
    // seng_mg: 5,
    // retinol_mcg: 500,
    // b_kar_mcg: 3600,
    // karoten_total_mcg: 4000,
    // thiamin_mg: 1.1,
    // riboflavin_mg: 1.1,
    // niasin_mg: 10,
    // vitamin_c_mg: 45,
  },
  2: {
    // TK B
    energi_kkal: 1400,
    protein_g: 25,
    lemak_g: 50,
    karbohidrat_g: 250,
    serat_g: 20,
    // abu_g: 5, // optional, tidak tercantum di AKG resmi
    // kalsium_mg: 1000,
    // fosfor_mg: 500,
    // besi_mg: 10,
    // natrium_mg: 1000,
    // kalium_mg: 3200,
    // tembaga_mg: 570,
    // seng_mg: 5,
    // retinol_mcg: 500,
    // b_kar_mcg: 3600,
    // karoten_total_mcg: 4000,
    // thiamin_mg: 1.1,
    // riboflavin_mg: 1.1,
    // niasin_mg: 10,
    // vitamin_c_mg: 45,
  },
  3: {
    //SD 1
    energi_kkal: 1650,
    protein_g: 40,
    lemak_g: 55,
    karbohidrat_g: 250,
    serat_g: 23,
    // abu_g: 5, // optional, tidak tercantum di AKG resmi
    // kalsium_mg: 1000,
    // fosfor_mg: 500,
    // besi_mg: 10,
    // natrium_mg: 1000,
    // kalium_mg: 3200,
    // tembaga_mg: 570,
    // seng_mg: 5,
    // retinol_mcg: 500,
    // b_kar_mcg: 3600,
    // karoten_total_mcg: 4000,
    // thiamin_mg: 1.1,
    // riboflavin_mg: 1.1,
    // niasin_mg: 10,
    // vitamin_c_mg: 45,
  },
  4: {
    // SD 2
    energi_kkal: 1650,
    protein_g: 40,
    lemak_g: 55,
    karbohidrat_g: 250,
    serat_g: 23,
    // abu_g: 5, // optional, tidak tercantum di AKG resmi
    // kalsium_mg: 1000,
    // fosfor_mg: 500,
    // besi_mg: 10,
    // natrium_mg: 1000,
    // kalium_mg: 3200,
    // tembaga_mg: 570,
    // seng_mg: 5,
    // retinol_mcg: 500,
    // b_kar_mcg: 3600,
    // karoten_total_mcg: 4000,
    // thiamin_mg: 1.1,
    // riboflavin_mg: 1.1,
    // niasin_mg: 10,
    // vitamin_c_mg: 45,
  },
  5: {
    //SD 3
    energi_kkal: 1650,
    protein_g: 40,
    lemak_g: 55,
    karbohidrat_g: 250,
    serat_g: 23,
    // abu_g: 5, // optional, tidak tercantum di AKG resmi
    // kalsium_mg: 1000,
    // fosfor_mg: 500,
    // besi_mg: 10,
    // natrium_mg: 1000,
    // kalium_mg: 3200,
    // tembaga_mg: 570,
    // seng_mg: 5,
    // retinol_mcg: 500,
    // b_kar_mcg: 3600,
    // karoten_total_mcg: 4000,
    // thiamin_mg: 1.1,
    // riboflavin_mg: 1.1,
    // niasin_mg: 10,
    // vitamin_c_mg: 45,
  },
  6: {
    //SD 4
    energi_kkal: 2000,
    protein_g: 50,
    lemak_g: 65,
    karbohidrat_g: 300,
    serat_g: 28,
    // abu_g: 5, // optional, tidak tercantum di AKG resmi
    // kalsium_mg: 1000,
    // fosfor_mg: 1250,
    // besi_mg: 8,
    // natrium_mg: 1300,
    // kalium_mg: 3900,
    // tembaga_mg: 700,
    // seng_mg: 8,
    // retinol_mcg: 500,
    // b_kar_mcg: 3600,
    // karoten_total_mcg: 4000,
    // thiamin_mg: 1.1,
    // riboflavin_mg: 1.3,
    // niasin_mg: 12,
    // vitamin_c_mg: 50,
  },
  7: {
    //SD 5
    energi_kkal: 2000,
    protein_g: 50,
    lemak_g: 65,
    karbohidrat_g: 300,
    serat_g: 28,
    // abu_g: 5, // optional, tidak tercantum di AKG resmi
    // kalsium_mg: 1000,
    // fosfor_mg: 1250,
    // besi_mg: 8,
    // natrium_mg: 1300,
    // kalium_mg: 3900,
    // tembaga_mg: 700,
    // seng_mg: 8,
    // retinol_mcg: 500,
    // b_kar_mcg: 3600,
    // karoten_total_mcg: 4000,
    // thiamin_mg: 1.1,
    // riboflavin_mg: 1.3,
    // niasin_mg: 12,
    // vitamin_c_mg: 50,
  },
  8: {
    //SD 6
    energi_kkal: 2000,
    protein_g: 50,
    lemak_g: 65,
    karbohidrat_g: 300,
    serat_g: 28,
    // abu_g: 5, // optional, tidak tercantum di AKG resmi
    // kalsium_mg: 1000,
    // fosfor_mg: 1250,
    // besi_mg: 8,
    // natrium_mg: 1300,
    // kalium_mg: 3900,
    // tembaga_mg: 700,
    // seng_mg: 8,
    // retinol_mcg: 500,
    // b_kar_mcg: 3600,
    // karoten_total_mcg: 4000,
    // thiamin_mg: 1.1,
    // riboflavin_mg: 1.3,
    // niasin_mg: 12,
    // vitamin_c_mg: 50,
  },
  9: {
    // SMP 1
    energi_kkal: 2400,
    protein_g: 70,
    lemak_g: 80,
    karbohidrat_g: 350,
    serat_g: 34,
    // abu_g: 5, // optional, tidak tercantum di AKG resmi
    // kalsium_mg: 1200,
    // fosfor_mg: 1250,
    // besi_mg: 11,
    // natrium_mg: 1500,
    // kalium_mg: 4800,
    // tembaga_mg: 795,
    // seng_mg: 11,
    // retinol_mcg: 500,
    // b_kar_mcg: 3600,
    // karoten_total_mcg: 4000,
    // thiamin_mg: 1.2,
    // riboflavin_mg: 1.3,
    // niasin_mg: 16,
    // vitamin_c_mg: 75,
  },
  10: {
    //SMP 2
    energi_kkal: 2400,
    protein_g: 70,
    lemak_g: 80,
    karbohidrat_g: 350,
    serat_g: 34,
    // abu_g: 5, // optional, tidak tercantum di AKG resmi
    // kalsium_mg: 1200,
    // fosfor_mg: 1250,
    // besi_mg: 11,
    // natrium_mg: 1500,
    // kalium_mg: 4800,
    // tembaga_mg: 795,
    // seng_mg: 11,
    // retinol_mcg: 500,
    // b_kar_mcg: 3600,
    // karoten_total_mcg: 4000,
    // thiamin_mg: 1.2,
    // riboflavin_mg: 1.3,
    // niasin_mg: 16,
    // vitamin_c_mg: 75,
  },
  11: {
    //SMP 3
    energi_kkal: 2650,
    protein_g: 75,
    lemak_g: 85,
    karbohidrat_g: 400,
    serat_g: 37,
    // abu_g: 5, // optional, tidak tercantum di AKG resmi
    // kalsium_mg: 1200,
    // fosfor_mg: 1250,
    // besi_mg: 9,
    // natrium_mg: 1700,
    // kalium_mg: 5300,
    // tembaga_mg: 890,
    // seng_mg: 11,
    // retinol_mcg: 500,
    // b_kar_mcg: 3600,
    // karoten_total_mcg: 4000,
    // thiamin_mg: 1.2,
    // riboflavin_mg: 1.3,
    // niasin_mg: 16,
    // vitamin_c_mg: 90,
  },
  12: {
    //SMA 1
    energi_kkal: 2650,
    protein_g: 75,
    lemak_g: 85,
    karbohidrat_g: 400,
    serat_g: 37,
    // abu_g: 5, // optional, tidak tercantum di AKG resmi
    // kalsium_mg: 1200,
    // fosfor_mg: 1250,
    // besi_mg: 9,
    // natrium_mg: 1700,
    // kalium_mg: 5300,
    // tembaga_mg: 890,
    // seng_mg: 11,
    // retinol_mcg: 500,
    // b_kar_mcg: 3600,
    // karoten_total_mcg: 4000,
    // thiamin_mg: 1.2,
    // riboflavin_mg: 1.3,
    // niasin_mg: 16,
    // vitamin_c_mg: 90,
  },
  13: {
    //SMA 2
    energi_kkal: 2650,
    protein_g: 75,
    lemak_g: 85,
    karbohidrat_g: 400,
    serat_g: 37,
    // abu_g: 5, // optional, tidak tercantum di AKG resmi
    // kalsium_mg: 1200,
    // fosfor_mg: 1250,
    // besi_mg: 9,
    // natrium_mg: 1700,
    // kalium_mg: 5300,
    // tembaga_mg: 890,
    // seng_mg: 11,
    // retinol_mcg: 500,
    // b_kar_mcg: 3600,
    // karoten_total_mcg: 4000,
    // thiamin_mg: 1.2,
    // riboflavin_mg: 1.3,
    // niasin_mg: 16,
    // vitamin_c_mg: 90,
  },
  14: {
    //SMA 3
    energi_kkal: 2650,
    protein_g: 65,
    lemak_g: 75,
    karbohidrat_g: 430,
    serat_g: 37,
    // abu_g: 5, // optional, tidak tercantum di AKG resmi
    // kalsium_mg: 1000,
    // fosfor_mg: 700,
    // besi_mg: 9,
    // natrium_mg: 1500,
    // kalium_mg: 4700,
    // tembaga_mg: 900,
    // seng_mg: 11,
    // retinol_mcg: 500,
    // b_kar_mcg: 3600,
    // karoten_total_mcg: 4000,
    // thiamin_mg: 1.2,
    // riboflavin_mg: 1.3,
    // niasin_mg: 16,
    // vitamin_c_mg: 90,
  },
};
export const NUTRIENT_LABELS = {
  energi_kkal: "energi",
  protein_g: "protein",
  lemak_g: "lemak",
  karbohidrat_g: "karbohidrat",
  serat_g: "serat",
  // abu_g: "Abu (g)",
  // kalsium_mg: "Kalsium (mg)",
  // fosfor_mg: "Fosfor (mg)",
  // besi_mg: "Besi (mg)",
  // natrium_mg: "Natrium (mg)",
  // kalium_mg: "Kalium (mg)",
  // tembaga_mg: "Tembaga (mg)",
  // seng_mg: "Seng (mg)",
  // retinol_mcg: "Retinol (mcg)",
  // b_kar_mcg: "Beta-Karoten (mcg)",
  // karoten_total_mcg: "Karoten Total (mcg)",
  // thiamin_mg: "Thiamin (mg)",
  // riboflavin_mg: "Riboflavin (mg)",
  // niasin_mg: "Niasin (mg)",
  // vitamin_c_mg: "Vitamin C (mg)",
};
